openapi: 3.0.0
info:
  title: Sample API
  version: 1.0.0
servers:
- url: https://d5dtnlbjpk4c8on6brdr.apigw.yandexcloud.net
paths:
  /{path+}:
    x-yc-apigateway-any-method:
      summary: API
      operationId: getVM
      tags:
        - example
      parameters:
        - name: path
          in: path
          required: false
          schema:
            type: string
      x-yc-apigateway-integration:
        type: http
        url: http://158.160.2.88:7777/{path}
        query:
          '*': '*'
        headers:
          '*': '*'
  
